Adjustmentを0.1単位で設定できる機能の追加
cwtickle/danoniplus pull request #1096
Opened 2021-08-31 15:57 UTC by suzme

## :hammer: 変更内容 / Details of Changes
- 曲開始位置をWebAudioAPIで微調整することでAdjustmentを0.1単位で設定できるようにしました

## :bookmark: 関連Issue, 変更理由 / Related Issues, Reason for Changes
- [Adjustmentが小数点以下で合わない](https://twitter.com/vdos2643/status/1429445149143146503)と感じる場合があるようです

## :camera: スクリーンショット / Screenshot

## :pencil: その他コメント / Other Comments
- 私は1f未満の差は正直よく分かりません
  - [自サイトに適用済](https://suzume.kirara.st/atmosphere/)なので分かる方に試していただけるとありがたいです
- WebAudioAPIが利用できない条件では小数点以下切り捨てで動作します

2021-08-31 22:05 UTC, cwtickle requested changes
お疲れさまです。
0.1単位のAdjustmentについてはこちらもわかりませんが、取り急ぎ問題となりそうな箇所だけご連絡します。

1. Adjustmentのカーソル位置がおかしい
    - Adjustmentが「0」のとき、左右に動かすと「-27」前後へ移動します。
    danoni_constants.js の Adjustment用のカーソル位置を示す「adjustmentNum」の値が、変更幅に対して変更されていないためと思われます。
<img src="https://user-images.githubusercontent.com/44026291/131580577-4e39aec0-fdae-4ba7-9775-688ccba859cf.png" width="90%">

```javascript
    adjustmentNum: C_MAX_ADJUSTMENT * 10;
```

2. 最内側のボタンのIDが重複
    - `makeMiniCssButton`の第二引数はID名に紐づくため、今のままだと最内側と内側のボタンIDが重複してしまいます。下記のような対処が必要だと思います。
```javascript
    makeMiniCssButton(linkId, `RRR`, 0, _ => setSetting(1, _settingName, unitName), {dw: -C_LEN_SETMINI_WIDTH / 2}),
    makeMiniCssButton(linkId, `LLL`, 0, _ => setSetting(1, _settingName, unitName), {dw: -C_LEN_SETMINI_WIDTH / 2}),
```
またこの場合、danoni_constants.js の g_settingBtnObj に、最内側ボタンの定義（表示文字、位置）を入れておく必要があります。
（下記コードは動作を見ずに書いているため、動作を確認してから入れるようにしてください）
```javascript
const g_settingBtnObj = {
    chara: {
        L: `<`,
        LL: `<`,
        LLL: `<`,  // 追加
        R: `>`,
        RR: `>`,
        RRR: `>`,  // 追加
        D: `↓`,
        U: `↑`,
    },
    pos: {
        L: C_LEN_SETLBL_LEFT - C_LEN_SETMINI_WIDTH,
        LL: C_LEN_SETLBL_LEFT,
        LLL: C_LEN_SETLBL_LEFT + C_LEN_SETMINI_WIDTH / 2, // 追加
        R: C_LEN_SETLBL_LEFT + C_LEN_SETLBL_WIDTH,
        RR: C_LEN_SETLBL_LEFT + C_LEN_SETLBL_WIDTH - C_LEN_SETMINI_WIDTH,
        RRR: C_LEN_SETLBL_LEFT + C_LEN_SETLBL_WIDTH - 3 * C_LEN_SETMINI_WIDTH / 2, // 追加
    }
};
```

2021-09-01 12:37 UTC, suzme commented
修正しました。
ショートカットキーはAlt同時押しを割り当ててみました。
(Shiftは既に割り当てられていて、Ctrlだとブラウザのズームと被るため)

2021-09-01 13:03 UTC, cwtickle approved these changes

2021-09-01 13:10 UTC, cwtickle commented
ありがとうございます！
変更箇所について、問題ないと思います。

問題の1フレーム未満の差ですが・・・
上記アドレスのNormalでざっくりプレイしてみた結果が下記です。
（いずれも曲中盤のフリーズアローの後で強制終了しています）
0.5フレーム差であれば何となくF/Sの量として違うかな、という気はします（確証はありません）。

- Adj: 2のとき：
<img src="https://user-images.githubusercontent.com/44026291/131676198-54037f62-6a67-4ac0-bbe6-2dae68421952.png" width="40%">

- Adj: 2.5のとき：
<img src="https://user-images.githubusercontent.com/44026291/131676323-31e33fc0-d95c-4c30-9d01-4d654cc95d2d.png" width="40%">

- Adj: 3のとき：
<img src="https://user-images.githubusercontent.com/44026291/131676477-ab12372b-d6c2-4b81-a0fb-fc5f2f95609b.png" width="40%">

2021-09-01 14:09 UTC, cwtickle commented
後からすみません、Gitterにコメントが来ていました（izkdicさんより）。
https://gitter.im/danonicw/community?at=612f7a61fd7409696ee9e933

確かにボタンが3種あって、通常良く使うと思われるボタンが真ん中にあるのは使いにくいかもしれません。
ただショートカットキーの割り当ては、物理的なボタンが無いとできないので、
lnkAdjustmentRR/LLボタンの裏に配置する、というのはどうでしょうか？

2021-09-01 14:57 UTC, cwtickle requested changes
後からすみません、Gitterにコメントが来ていました（izkdicさんより）。
https://gitter.im/danonicw/community?at=612f7a61fd7409696ee9e933

確かにボタンが3種あって、通常良く使うと思われるボタンが真ん中にあるのは使いにくいかもしれません。
ただショートカットキーの割り当ては、物理的なボタンが無いとできないので、
lnkAdjustmentRR/LLボタンの裏に配置する、というのはどうでしょうか？

2021-09-01 16:29 UTC, suzme commented
隠してしまうと知らずに押してしまった人が戻せなくなりそうです。
対策として±1や±5のボタンを小数点以下切り捨て動作にすることを考えています。

2021-09-01 21:55 UTC, cwtickle commented
ご意見ありがとうございます。
そうですね、ショートカットキーの場合誤操作があったときに復旧手段が無いと困るかもしれないです。
±1や±5のボタンを小数点以下切り捨て操作する（実際にはAdjustmentのカーソル位置を変更する）方法で問題ないと思います。

ボタンを非表示にしながらショートカットキーを有効にする例としては下記の例があります。
（Density -> ToolDifへの移動ボタンの逆操作）
裏に表示するボタンを先に定義したうえで、仮に表に出ているボタンが座標移動されてもいいように
visibility属性を `hidden` に設定しています。
<img src="https://user-images.githubusercontent.com/44026291/131749706-884e7fdc-25de-4d86-82ba-f3f00059e6b8.png" width="70%">

お手数をお掛けしてすみませんが、よろしくお願いします m(_ _)m

2021-09-01 22:32 UTC, cwtickle commented
連投すみません。
下記の作品で動作確認していて気づいたのですが、
フェードイン有効時にエラーなく音楽が鳴らず、譜面も流れてこない事象が出ています。
https://suzume.kirara.st/atmosphere/

3x Brake、フェードイン38％で確認しましたが、フェードイン位置は他でも発生しました。
多分、これまでは譜面のフレーム数を直接修正していましたが、曲側で変えるようにしたことが影響しているように思います。

2021-09-02 11:40 UTC, cwtickle commented
Adjustmentの刻み幅については、今の時点で0.5より細かい幅を求めている人が少ないので、
0.5フレーム幅で様子を見る、でもいいのかもしれません。
（最近のバージョンで設定画面の押しっぱなしを解禁しましたが、
　それでも0.5にするには5回押さないといけないため）

2021-09-02 14:09 UTC, suzme commented
fadeinの問題を修正しました。確認不足でした。

2021-09-03 09:40 UTC, cwtickle commented
ありがとうございます。
ソース適用してみましたが、フェードインについて状況変わりませんでした。
ローカル(XAMPP)で確認する限りでは、メイン画面に移動した後同じフレーム数でずっと止まってしまう状態です。

2021-09-03 10:53 UTC, suzme commented
すみません、正しくコミットできていなかったみたいです……。
念のため修正内容は以下です(8740行目)。

```js
//誤
const musicStartAdjustment = (firstFrame + g_headerObj.blankFrame - g_stateObj.realAdjustment) / g_fps;

//正
const musicStartAdjustment = (g_headerObj.blankFrame - g_stateObj.realAdjustment) / g_fps;
```

修正間の差分が見れないので`--amend`して`push --force`するのはやめたほうがいいのかなと今更思いました。

2021-09-03 12:33 UTC, cwtickle commented
ありがとうございます m(_ _)m
フェードインでも問題なく動作することを確認しました。
コミットについては、途中過程見る意味でも切りの良いところで適宜コミットしてもらって構わないです。

後は下記でしょうか。
- 最内側のAdjustmentボタンを隠す
- Adjustmentの最も細かい刻み幅を0.1 -> 0.5にする
- 内側のAdjustmentボタンを押したとき、整数に戻るようにする

2021-09-04 00:07 UTC, cwtickle commented
Gitterにてaconiteさんからご意見いただいているのでアドレス載せます。
https://gitter.im/danonicw/community?at=61326f5167e789189cdb37b0

刻み幅については需要が無ければ0.5単位でいいのではないかと思いましたが、
0.1単位でも精度勢には一定の需要がありそうなので、
内側: 0.5F刻み（カーソル移動時は0.5Fで丸める） / Altショートカット: 0.1F刻みで良いと思いました。

> 適切なAdj設定には0.5Fの幅があると思われ、Adjは0.5刻みで設定できればギリギリ十分だと考えられます。
> しかし、プレイヤーの打鍵タイミングが正しいタイミングを中心に正規分布を取ると仮定した場合、
> 分散が大きい譜面(難譜面・細かい音取りが多い譜面・多鍵譜面)ではAdj設定と
> 正しいタイミングとの微細なズレがより大きくリザルトに影響すると考えられます。
> 以上をふまえて、基本は0.5刻みで、ショートカットキーを使うと0.1刻みで調整できる、
> という仕様だと一番ありがたいです。

2021-09-04 09:08 UTC, suzme commented
一通り対応しました。
0.5刻みになるとShiftショートカットの±5fが遠すぎると思うので±3fにしてみました。

2021-09-04 09:27 UTC, cwtickle approved these changes
ご対応いただき、ありがとうございます m(_ _)m
結局結構手を入れる形になってしまいましたね。
細部微調整はいるかなと思いますが、機能的にはこれで完成で良いと思うのでマージしておきます。

2021-09-04 09:27 UTC, merged