空押し判定を実装
cwtickle/danoniplus pull request #1503
Opened 2023-06-10 05:41 UTC by goe0

## :hammer: 変更内容 / Details of Changes
空押し判定を導入しました。譜面ヘッダーとsettingsで使用可否を設定でき、デフォルトはOFFです。
Flash時代のプギャー判定とは以下の点で仕様が異なります。
- 全区間で判定するのではなく各ノーツの-16Fまでを判定
- ダメージは通常ダメージの1/4
- 判定はウワァンとしてカウント（リザルトでは「見逃し数(+空押し数)」で表示）

## :bookmark: 関連Issue, 変更理由 / Related Issues, Reason for Changes
固定運指可能key(5,7,7i,9A,9Bなど)でゲージ甘めの高密度譜面だと全押し連打でクリアできることがあり、その対策のため

## :camera: スクリーンショット / Screenshot

![empty_jdg](https://github.com/cwtickle/danoniplus/assets/44545711/b271d2e3-96f2-42ed-bcc2-a2ae15325ddf)

## :pencil: その他コメント / Other Comments
あまり見ないケースですがg_judgObj.arrowJ の4番目と5番目の値を別にしている作品がある場合、判定処理に影響を与えます

2023-06-10 07:33 UTC, cwtickle commented
@goe0 
PRありがとうございます！　空判定の選択肢を入れることについては問題ないと思います。
個人的にいくつか気になる点がありましたのでコメントします。

### 1. リザルト画面での判定表記
- 空押しは表示自体は確かに判定ですが、総矢印数の内数に入らないので
どちらかといえばFast/Slow的な位置づけに近いのかなと思いました。
例えば、空判定数を推定Adj欄の下に入れるのはどうでしょうか？

### 2. プレイ画面上の空判定表記
- 今の実装だとウワァンにまとめていると思いますが、
1.に合わせて従来のようにプギャーとして独立させた方がわかりやすいように思いました。
空判定数を下記のように載せるかどうか（入れるとするなら、フリーズコンボ欄から一段空白を入れてその下か）
は個人的には入れても入れなくてもといった感じです。

<img src="https://github.com/cwtickle/danoniplus/assets/44026291/142e0d18-031a-4b43-8ad9-c9586699bfce" width="10%">

2023-06-10 08:10 UTC, cwtickle commented
使う側の意見が必要そうだったので、DiscordのソースチャンネルにこのPRのリンクを張りました。
https://discord.com/channels/698460971231870977/944491021918683196/1116994364758036530

2023-06-11 02:31 UTC, cwtickle requested changes
Discordでさまざまコメントが出ていますが、こちらではコード上の気づいた点を上げます。

### emptyJdgUse有効時、ゼロで終了したときの表示がおかしい
- 下記のように、矢印を1つも取らずに終了した場合にウワァンが`NaN(+undefined)`になります。ウワァンがゼロで終了した場合でも同様です。
条件がわかりませんでしたが、`NaN(+NaN)`のように出ることがあります。

<img src="https://github.com/cwtickle/danoniplus/assets/44026291/f3c360c8-4779-4010-a810-ba65f125bf52" width="50%">

- おそらく初期化周りの問題だと思います。`g_resultObj`の要素として追加するのであれば、
danoni_constants.jsで初期化した方が初期化漏れを防げます。

<img src="https://github.com/cwtickle/danoniplus/assets/44026291/6922e9ab-f2da-4e4d-93e5-f15c96ab6c1f" width="40%">

2023-06-11 04:22 UTC, goe0 commented
ありがとうございます。修正しました。
議論により判定名が変わるかもしれませんが、一旦emptyUwanのままとしています。

2023-06-14 12:34 UTC, cwtickle approved these changes
ありがとうございます。
追加で変更があると思いますが、今のところ問題点は直っていますのでApproveします。

2023-06-23 00:58 UTC, goe0 commented
Discord上の議論を反映し、空押し判定のウワァンから独立、オプション化などを行いました。
displayDiffに処理をまとめたことで、変更前よりシンプルな実装になったかと思います。

2023-06-23 10:07 UTC, cwtickle requested changes
@goe0 
ありがとうございます。コード確認しました。
概ね問題無いと思いますが、次の2点だけ。

### displayDiff の条件式
- Excessiveの条件式が`_difFrame > g_judgObj.arrowJ[g_judgPosObj.shobon]`になっていますが、`_difFrame`は正負の値を含んでいるので、`difCnt`が正しいでしょうか？
（Excessiveがショボーンの両端をカバーするのであれば）

### Excessiveの説明文（英語）について
- 空押し＝Excessive Missのようなので、"Excessive miss judgment"かと思います。

2023-06-24 05:07 UTC, goe0 commented
ご確認ありがとうございます。修正しました。

2023-06-24 05:16 UTC, goe0 commented
追加ですみませんが、空押し判定OFFのときのTwitterリザルトの出力内容を修正しました。

2023-06-24 07:25 UTC, cwtickle approved these changes
空押し判定OFFのときのリザルト表記については分岐必要でしたね。確認しました。
本来実施する範囲の内容としては問題無いと思いますので、この内容でマージします。
お疲れさまでした m(_ _)m

2023-06-24 07:26 UTC, merged