フリーズアローの判定処理を修正
cwtickle/danoniplus pull request #1627
Opened 2024-03-13 14:07 UTC by goe0

## :hammer: 変更内容 / Details of Changes
- フリーズの終点と次のフリーズの始点が近いとき、キーを押しても次のフリーズが判定されないことがあるバグを修正

## :bookmark: 関連Issue, 変更理由 / Related Issues, Reason for Changes

フリーズAの終点と次のフリーズBの始点が近いとき、
Aを見逃しイクナイで判定するとBの始点でキーを押しても反応しないというバグが報告される https://github.com/cwtickle/danoniplus/issues/1529
（途中離しイクナイなら反応し、早押しイクナイは実質的に見逃しイクナイと同等の処理になるので反応しない）

↓

https://github.com/cwtickle/danoniplus/pull/1530 にて修正される

↓

Speedの速さなどにより、Bが作成済みか否かで現象が分岐するようになる
1. Bが作成済みのとき、Aが削除されるので反応する
2. Bが未作成のとき、Aが削除されないので反応しない
おそらく1の条件のみをチェックしたのでプルリクが取り込まれてしまった

↓

Aを削除するのではなく、judgeArrow にて判定を次のフリーズに移すことで対応しました

## :camera: スクリーンショット / Screenshot

## :pencil: その他コメント / Other Comments

2024-03-14 03:28 UTC, cwtickle commented
PRありがとうございます。
確かにその方がわかりやすいかもしれませんね。

なお変更したコードにある「g_workObj.judgFrzCnt[_j]」ですが、
矢印・フリーズアローのオブジェクトを削除したときにカウントアップしています。
<img src="https://github.com/cwtickle/danoniplus/assets/44026291/a05915c3-4769-4b44-b33a-ae31e1c3b10d" width="70%">

発生頻度はあまりないと思いますが、判定時と消去時で時間差ができるので
```js
if (currentFrz?.judgEndFlg) {
```
の部分はwhileに変えておいた方が良いのかもしれません。（要検証）

PRで変更頂いたソースは試験的に下記サイトで動作確認できるようにしました。
https://danonicw.skr.jp/?v=v35.4.2-a1

2024-03-14 12:25 UTC, cwtickle commented
上記サイトで検証してみました。
下記のデータで試したところ、途中で止まることを確認しました。
```
|stepY=120|
|frzDown_data=200,235,237,240,243,270|
```
<img src="https://github.com/cwtickle/danoniplus/assets/44026291/01df7284-2460-46c4-8c4e-11b13be84906" width="70%">

<img src="https://github.com/cwtickle/danoniplus/assets/44026291/1d7d28fe-f55a-4854-8205-4eeec7d4428c" width="70%">

2024-03-14 13:11 UTC, cwtickle requested changes
stepY=70（デフォルト）でも再現したので、コードの見直しが要ると思います。
ちなみに上で言っていたif -> whileにしても変わらなかったので、別原因かと。

2024-03-14 17:33 UTC, goe0 commented
ご確認ありがとうございます。
再度調査したところ元々は https://github.com/cwtickle/danoniplus/pull/1376 の修正が原因だったようです。
強制削除は行うが判定は重複しないように条件を修正しました。

自環境でテストし https://github.com/cwtickle/danoniplus/pull/1376 および https://github.com/cwtickle/danoniplus/pull/1530 双方の問題が解決していることを確認しましたが、
このあたり処理が複雑なのでまた別のバグが発生している可能性もあります。

2024-03-15 10:57 UTC, cwtickle commented
ありがとうございます。
先ほどの問題は解消していることを確認しました。
念のため、Discordの方で確認して問題なければマージするようにしますね。

2024-03-17 13:09 UTC, cwtickle approved these changes

2024-03-17 13:10 UTC, merged